/*
	filename: GuessingGame.cpp
	Author: J. Hayes
	Date: Sep, 19, 2019
	Purpose: To solve Programming challenges 20 & 21.
		In this problem the user is to guess what random number (0-100) 
		was generated by the computer.
*/

#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

int main()
{
	int guess; // User's guess
	int count; // Count the number of guesses 

	// Get the system time to seed the random number generator
	unsigned seed = time(0);
	// Intialize the random number generator
	srand(seed);
	// Generate a random number between 1 and 100.
	int number = 1 + rand() % 100;

	// Get the user's guess
	cout << "The computer is thinking of a random number. ";
	cout << "Can you guess it? ";
	cin >> guess;

	// Intialize the counter
	count = 1;
	// Respond to the user's guess
	while (guess != number)
	{

		if (guess < number)
			cout << "No, that's too low. Try again\n";
		else if (guess > number)
			cout << "Sorry, that's too high. Try again.\n";
		// Another guess
		cout << "Guess again: ";
		cin >> guess;
		// Increment the counter
		count++;
	}	// end while

	cout << "Congragulations! You guessed it!\n";
	cout << "The number was " << number << ".\n";
	cout << "You guessed it right in " << count << " guesses.\n";


	

}	// end main()